export const A = {
  FAILURE: "FAILURE",
  ALERT_ERROR: "ALERT_ERROR",

  CREATE_COURSE: "CREATE_COURSE",
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",

  LOAD_NAVIGATION_REQUEST: "LOAD_NAVIGATION_REQUEST",
  LOAD_NAVIGATION_SUCCESS: "LOAD_NAVIGATION_SUCCESS",
  LOAD_NAVIGATION_FAILURE: "LOAD_NAVIGATION_FAILURE",

  GET_SERVICE_DATA_REQUEST: 'GET_SERVICE_DATA_REQUEST',
  GET_SERVICE_DATA_SUCCESS: 'GET_SERVICE_DATA_SUCCESS',
  GET_SERVICE_DATA_FAILURE: 'GET_SERVICE_DATA_FAILURE',
};
